use_frameworks!

platform :ios, '9.0'

target 'JWAlertView_Example' do
  pod 'JWAlertView', :path => '../'

  target 'JWAlertView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
